version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: .docker/staging/Dockerfile
        container_name: hrms
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
